CREATE TABLE USER_ROLES(
    ID INT NOT NULL AUTO_INCREMENT, 
    UserType VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER_ROLES (UserType) VALUES ('Admin');
INSERT INTO USER_ROLES (UserType) VALUES ('Customer');
